"""add lead next_action_date

Revision ID: 7fd5270f661c
Revises: 5cdff1fb28f5
Create Date: 2026-02-13 22:02:17.146329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd5270f661c'
down_revision = '5cdff1fb28f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_action_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_next_action_date'), ['next_action_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_next_action_date'))
        batch_op.drop_column('next_action_date')

    # ### end Alembic commands ###
