"""staff-v1 multi-tenant communications and integrations

Revision ID: db3c29634140
Revises: 7fd5270f661c
Create Date: 2026-02-13 22:31:22.582924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3c29634140'
down_revision = '7fd5270f661c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_rules_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_rules_created_at'), ['created_at'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_hash', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)

    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('e164', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phone_numbers_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phone_numbers_created_at'), ['created_at'], unique=False)

    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('stage_key', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'stage_key', name='uq_pipeline_stage_key')
    )
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_stages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_stages_created_at'), ['created_at'], unique=False)

    op.create_table('provider_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=40), nullable=False),
    sa.Column('encrypted_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_credentials_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_credentials_created_at'), ['created_at'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('signature_ok', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_events_provider'), ['provider'], unique=False)

    op.create_table('conversion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('gclid', sa.String(length=255), nullable=True),
    sa.Column('conversion_name', sa.String(length=100), nullable=False),
    sa.Column('conversion_time', sa.DateTime(), nullable=False),
    sa.Column('conversion_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversion_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_events_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_events_gclid'), ['gclid'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_events_lead_id'), ['lead_id'], unique=False)

    op.create_table('lead_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_payloads_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_payloads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_payloads_lead_id'), ['lead_id'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('from_number', sa.String(length=40), nullable=False),
    sa.Column('to_number', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recording_url', sa.String(length=255), nullable=True),
    sa.Column('provider_call_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_provider_call_id'), ['provider_call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_status'), ['status'], unique=False)

    op.create_table('consent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('consent_type', sa.String(length=80), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_events_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_events_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_events_patient_id'), ['patient_id'], unique=False)

    op.create_table('contact_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('phone_e164', sa.String(length=40), nullable=True),
    sa.Column('whatsapp_e164', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_identities_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_identities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_identities_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_identities_patient_id'), ['patient_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_patient_id'), ['patient_id'], unique=False)

    op.create_table('call_dispositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('followup_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_dispositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_dispositions_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_dispositions_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_dispositions_created_at'), ['created_at'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('template_name', sa.String(length=80), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_provider_message_id'), ['provider_message_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_trips_patient_id'))

    op.drop_table('trips')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('default_currency', sa.String(length=8), nullable=False, server_default='EUR'))
        batch_op.add_column(sa.Column('default_language', sa.String(length=12), nullable=False, server_default='it'))
        batch_op.add_column(sa.Column('languages_json', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.create_index(batch_op.f('ix_clinics_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_key', sa.String(length=40), nullable=False, server_default='new'))
        batch_op.add_column(sa.Column('landing_page_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('referrer_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('utm_medium', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('utm_term', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('utm_content', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gclid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fbclid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('ip_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_index('ix_lead_clinic_created', ['clinic_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_assigned_agent_id'), ['assigned_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_gclid'), ['gclid'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_leads_deleted_by_users', 'users', ['deleted_by'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_doctor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clinical_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_assigned_doctor_id'), ['assigned_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_patients_deleted_by_users', 'users', ['deleted_by'], ['id'])
        batch_op.create_foreign_key('fk_patients_assigned_doctor_users', 'users', ['assigned_doctor_id'], ['id'])
        batch_op.drop_column('medical_notes')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_clinic_status'))
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quotes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_quotes_deleted_by_users', 'users', ['deleted_by'], ['id'])

    with op.batch_alter_table('treatment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_plans_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('treatment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_plans_created_at'))

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quotes_status'))
        batch_op.drop_index(batch_op.f('ix_quotes_patient_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_lead_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_quotes_created_at'))
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.create_index(batch_op.f('ix_payment_clinic_status'), ['clinic_id', 'status'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_notes', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_patients_created_at'))
        batch_op.drop_index(batch_op.f('ix_patients_assigned_doctor_id'))
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('clinical_notes')
        batch_op.drop_column('assigned_doctor_id')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_gclid'))
        batch_op.drop_index(batch_op.f('ix_leads_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_leads_created_at'))
        batch_op.drop_index(batch_op.f('ix_leads_assigned_agent_id'))
        batch_op.drop_index('ix_lead_clinic_created')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('ip_hash')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('fbclid')
        batch_op.drop_column('gclid')
        batch_op.drop_column('utm_content')
        batch_op.drop_column('utm_term')
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')
        batch_op.drop_column('referrer_url')
        batch_op.drop_column('landing_page_url')
        batch_op.drop_column('stage_key')

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_created_at'))
        batch_op.drop_column('languages_json')
        batch_op.drop_column('default_language')
        batch_op.drop_column('default_currency')
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_created_at'))

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))
        batch_op.alter_column('action',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('trips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('arrival_date', sa.DATE(), nullable=True),
    sa.Column('departure_date', sa.DATE(), nullable=True),
    sa.Column('hotel_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('airport_pickup', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_clinic_id'), ['clinic_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_quote_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_invoices_created_at'))
        batch_op.drop_index(batch_op.f('ix_invoices_clinic_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_messages_clinic_id'))

    op.drop_table('messages')
    with op.batch_alter_table('call_dispositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_dispositions_created_at'))
        batch_op.drop_index(batch_op.f('ix_call_dispositions_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_call_dispositions_call_id'))

    op.drop_table('call_dispositions')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_patient_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_lead_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_external_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_clinic_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('contact_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_identities_patient_id'))
        batch_op.drop_index(batch_op.f('ix_contact_identities_lead_id'))
        batch_op.drop_index(batch_op.f('ix_contact_identities_created_at'))
        batch_op.drop_index(batch_op.f('ix_contact_identities_clinic_id'))

    op.drop_table('contact_identities')
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_events_patient_id'))
        batch_op.drop_index(batch_op.f('ix_consent_events_lead_id'))
        batch_op.drop_index(batch_op.f('ix_consent_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_consent_events_clinic_id'))

    op.drop_table('consent_events')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_status'))
        batch_op.drop_index(batch_op.f('ix_calls_started_at'))
        batch_op.drop_index(batch_op.f('ix_calls_provider_call_id'))
        batch_op.drop_index(batch_op.f('ix_calls_patient_id'))
        batch_op.drop_index(batch_op.f('ix_calls_lead_id'))
        batch_op.drop_index(batch_op.f('ix_calls_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_calls_created_at'))
        batch_op.drop_index(batch_op.f('ix_calls_clinic_id'))

    op.drop_table('calls')
    with op.batch_alter_table('lead_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_payloads_lead_id'))
        batch_op.drop_index(batch_op.f('ix_lead_payloads_created_at'))
        batch_op.drop_index(batch_op.f('ix_lead_payloads_clinic_id'))

    op.drop_table('lead_payloads')
    with op.batch_alter_table('conversion_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_events_lead_id'))
        batch_op.drop_index(batch_op.f('ix_conversion_events_gclid'))
        batch_op.drop_index(batch_op.f('ix_conversion_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversion_events_clinic_id'))

    op.drop_table('conversion_events')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_provider'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_events_clinic_id'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_credentials_created_at'))
        batch_op.drop_index(batch_op.f('ix_provider_credentials_clinic_id'))

    op.drop_table('provider_credentials')
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stages_created_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_stages_clinic_id'))

    op.drop_table('pipeline_stages')
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phone_numbers_created_at'))
        batch_op.drop_index(batch_op.f('ix_phone_numbers_clinic_id'))

    op.drop_table('phone_numbers')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_clinic_id'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('assignment_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_rules_created_at'))
        batch_op.drop_index(batch_op.f('ix_assignment_rules_clinic_id'))

    op.drop_table('assignment_rules')
    # ### end Alembic commands ###
